---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rybbit-helm-values
  namespace: rybbit
spec:
  encryptedData:
    values.yaml: AgDDRvMhHZ0SkExL84VdnNv4RTLpFQYZuxpgCPAsGX/5mAzAdinMUq3Lo3VwB3ton82QB3uWLzg3chxQsHJfnIggZnHkiwZ//+b8WUt20Hc/vA0CnZskXTxoVAs97NsZL8vVVA3hmBtzZOZICiDsXh5mlOVvXrvcQT0VC1AHqVkaMwzEidOX0PqUAyovb0iZY+RkPRknqXyhDH61Hp/9Vh8oArc5twpQJYZmrSv4OMLIrNCMt/4y/5xQVmzz70lL2qC98XxA0OZtSO7YNqF6qzNGXRyAHSY+GRg/MQ02Xi6FEMugn1z5j4AL8L77/MBxf0rHhg4u9IuglLDZQgOl+EgEzUgtlkIeN70EUtFhIjAVSTDXHzyrsyqUSwEba0sEsRb0/sii5dhSXrAbSZmMHtelAW4KmLkOuc2bRk64qzIHsPECesFtfBiydyjtWemnGaYqIxd4hrx0KjCh4LfTmEQyLlDzYwNul9vQPhVFqhYIxFad+YDnXWVSuFRAlEpeQBKMUU03q7uUHGQIZW4n/046iS7B6JgCARbkVL77WBlKTruoRO26xj/xTmhDv5MU5CaycnuGhPTIn6ehS5AHUXm8M4j/phJei3nL/Y8n0dAKYV87aehTQoZlVsILA3bPwXvORyVY4UbmN9HgpSJh5ErOGdtwvjNQhYnmz3G1QAMNBdV4taZOZr5Gtb7tGIv4v4eq0b0=
  template:
    metadata:
      creationTimestamp: null
      name: rybbit-helm-values
      namespace: rybbit
    type: Opaque
