---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rybbit-helm-values
  namespace: rybbit
spec:
  encryptedData:
    values.yaml: AgBgqIxxmqdf5ptd0NEKdjWpDLfGHwnJR97NUgUX+PvfkKnpfGPElaV+u8xxnwDGOD6bD/Ld8ty7qmyvwvC62YFMvVQ+pGGi5xdoxEJ1OAb4JfRn6QUvNIFu0g9D4Dv6waf2Y3kRnb0ZQTAJJuobOiAI3nNO9r7vDfc411gQDTnlokK54OVQ2FUzxETUvbXqvEEg9QLaj2TjPjyAuLURbBU9dehy3s9Chtr16D3dfnUSvKo0B8zME983hxh7qJCHoOi99TjgnHvIz5aoMNysKHA6z1vrkldccOEa3BjBAMnZ7Qdg+Kuc96u+N6eocR/sB3pvVSVO9z67uUdn79oPY75ARpF9vJY09U74aEddMbnVW7GtOXGOgVeiU7QzvlfxArb4zToPJj+YbpOpIovz96hlc/wjeflnl6GdGEZQglLQTK4iVD0NVlMPS49xx4T9myrjVm2w3MtiBVjh/xgfNjnbZ55rTCuMAsQVaebgj9xuy8IcRbEg50ievk8BslCZNi8XjMQswtK7qWCCBtNtxdA1FtS3VXqZDbSKr5jjyI5Uk3mVlCMdHnn3Q/2yF6doYMI0w/VD/eV1bDlI8i8oYbliP9TkJtPZw2m9Ue1P4UrIiYfL4fHPrNBiTzK/vF70W/iA/4uxPo0V9XgLuKCrNISzRVGlvRzZOeN5Io2lvC96ng3GfS8dCxhuzssYryfQXndN9eC7S1aaLDCj38dBIzrf+UY64wxiAOrPEzLuTsbjWdPqlrz/6Z53r8NZn2I6+Kr+kfvDxDb9Sq+XfcqTTrqyMaB+ZPRLk011zH8PTtdzuzTWT0VCivLPlyQqqYq9jy3k3jPDkutTmCpVtWSYVEyQdJBNeh1GHV7eOUBFvcvy6M0zYRaU1w==
  template:
    metadata:
      creationTimestamp: null
      name: rybbit-helm-values
      namespace: rybbit
    type: Opaque
