---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rybbit-helm-values
  namespace: rybbit
spec:
  encryptedData:
    values.yaml: AgBptC8GPQyHx+mJj8DqOG26fzDJU+TAN21HwRMzVMpap0cLnRjF7QOmnkWeBb7eohzkZ+B3x3vROqG992cB89QyjLcfbSmCchhKNwmoWT2if5w/NFKK2JppXbyYxchW2VBa55EkJrKrlqA2PI8G8COVVYXCTD0OQkTplJ9xGYqeDRtDYCnNVbhGognISiUCXtCeJyijx7Zt9h0jsKBdrzMpq8mVE/UkTiqVkcS88ImaB0rwyZwevTVh6hZ6++vVAanYfBZLsAgZ5KM95X4oW40RflV0w8Tf3HfxO2Jee4ihCoHXd0CVIDOAJ2eUmLoytGodQ6fZTU0tYIdY2m241WegWfTMBAqqBWyUP7ZVG6fPcU6cWyuqyRWWirNiinTUOKhEcuPLvMlDdmrM9MJ4AavpE4whXiMb48dr6v5qgRYXFuSI17EIph6IUrcMJR5ZFrf2LCRbltlrkp1lPYnZJkFBjR89/joFqCf+9zHbuizydWvZ37Jj99P01HcXnf7BzcwLY5DQP9IfLuQnaavuPGhbiPaw2NOu8RE0enQrH93tV/UbILVatDWeAT8Z9nAsfII7zsV3tKAYevCR1kQbPiaBwivqQP4eUlOLu/Y5rmHSBYMchA6DCEIzfBB0tpanK0oGj7tlNO2xCSNpnhoY8PPtO95QgzDwP1WrZit1keX7XOnS5bM1m1SNwHQtDuowIEhXbMjfhUaS6SSCiTzeE/hZFYOD0gzr7Bn3lY4G6E0x7VFTaPiVTSrSm9ClLUmHCrvgQUlLLbm077u3NSNx9WzINnZpd4wiN4O9Ro7gtBAnmryqY6/aaYbH6sWPtstvFiSg8tbN5cxprZP65pjUfweM
  template:
    metadata:
      creationTimestamp: null
      name: rybbit-helm-values
      namespace: rybbit
    type: Opaque
