---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rybbit-helm-values
  namespace: rybbit
spec:
  encryptedData:
    values.yaml: AgCl26t1kBNyvdEZwy3A1qU+R4uhWU5VgaRJtl9t9Ki5C2VhBlud3WBJQ6ep6K8//eugCyPTp2+dhrcaohzeL+skZRA9xcm5+/sCiL8P/P4tsjeljCdwmjaSEhJuwVCnrVPAZI4AiGpValKfNDqsqukuN/f9I8j3pv1LmQwJsIk+TZoBCr8+v6uibV3HT2tjTezrzFzL0+4BjI9jEJIPou8Gzr9tAWNxmc1NRoXrh0JpK7Gh5Dz9v9txzKVXw+f8XDlhIc3oJt8i7ynyvfmyJDVYWbqMXzRXDqP/BA0YPZJf92cOPaA4r8wz5G3snTGiSVMsoSc401H+v1UkcP6YO18VxSy5dc9/mScqJ9FpFlzPMit08EfjkPAcHpOhOK4uQUp83dUghVhzul7gSJdFxTrDMEJ5Rk2yrUbkzXWrNqHE28PhNjiL/qJENlGW85VlLY1YLFw4julz78oT8L0FkYmUwG2HFRa0SCIFUv2cPVttTEsbir2FO6YMiu+7uJLZMzkQscQK4eSyj04pXrj/WUrbc4uF6baEdEPF41B2nPqPApnNO/BcHVCzpgkXlYt99A3nF2NwxskL4hOhdYknd5/hZpSkMWB7hJ/8kpjghjkv1yf2dt1pm+8o4QIuE3RjqwznH9TglvUoeaRXkQAp7Ky2wTuT5Extbzpepvi4nFStcBs055fR1QVehvLc/RTO5Ez3UU2l7/9KvRG0g9OU1EkL1RaE/XNOPmRSdv5g88A+E3WsW2OsXEOFUdVMJ/DfDMhGdAHaicL8i6eCmqOQ728E3+NnaegXYFko/LMiGLIDp2Wc5YDkF8ZAs/OJ3rTmu7az8T6o6/KHkcyUQGozdAQSUKwz0/76clk7pMGOlLXmLbChSA9hWkOGFkV6ywWktkKEGpURiBehCTQ+Cdvjps4sX9hVfB/Jkp/Xwwyc4sl1NPLbiIrg3QYonHCLyMnYjRot2LDa/WY5tA==
  template:
    metadata:
      creationTimestamp: null
      name: rybbit-helm-values
      namespace: rybbit
    type: Opaque
