apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-credentials.sealed.yaml
  - rybbit-secrets.sealed.yaml
  - clickhouse-credentials.sealed.yaml
  - helm-values.sealed.yaml
  - postgres-cluster.yaml
  - release.yaml
  - ingress.yaml
